#!/usr/bin/env bash

set -e

run=$(dirname "$0")/run
rm -rf target-ubuntu/AppDir
$run cargo build

neovide=target-ubuntu/debug/neovide

#mkdir -p AppDir/usr/bin
#cp $neovide AppDir/usr/bin/

#$run appimage-builder

$run linuxdeploy \
    --executable=$neovide \
    --desktop-file=assets/neovide.desktop \
    --appdir=target-ubuntu/AppDir \
    --icon-file=assets/neovide.svg \
    --output=appimage

 mv Neovide_\(nvim\)-*.AppImage neovide.AppImage
