name: neovide # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: "0.10.4+git"
summary: The snappiest vim editor you are likely to find.
description: |
  This is a simple graphical user interface for Neovim. Where possible there are some graphical improvements,
  but it should act functionally like the terminal UI.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots
lint:
  ignore:
    - classic:
      - usr/lib/${CRAFT_ARCH_TRIPLET}/dri/*
    - library:
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libEGL.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libEGL_mesa.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libGL.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libGLU.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libGLX.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libGLX_mesa.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libGLdispatch.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libOpenGL.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libX11.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libXcursor.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libXext.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libXfixes.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libXi.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libXrandr.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libXrender.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libXxf86vm.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libgbm.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libicui18n.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libicuio.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libicutest.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libicutu.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libwayland-client.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libwayland-server.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libxcb-dri2.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libxcb-glx.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libxcb-present.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libxcb-render.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libxcb-shm.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libxcb-sync.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libxcb-xfixes.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libxcb-xkb.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libxkbcommon-x11.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libxkbcommon.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libxshmfence.so.*
      - usr/lib/${CRAFT_ARCH_TRIPLET}/libwayland-egl.so.*
parts:
  # The mesa drivers can't be patched, see various issues on the snap forums
  mesa-nopatchelf:
    plugin: nil
    stage-packages:
    - libgl1-mesa-dri
    build-attributes:
      - no-patchelf
    stage:
      - usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri

  # These libraries are dynamically loaded, and can't be verified automatically
  # by the linter. So you need to manually verify which packages are needed at
  # runtime. You can use for example /proc/<pid>/maps, to see where each so
  # file is loaded from. This needs to be done for both Wayland and X11, and a
  # combination of all libraries should be included. A corresponding line also
  # needs to be added to the linter ignore list.
  # If you remove this part completely, the snap should still build without
  # linter errors, so that's a good way to check that you have everything
  # needed in the normal neovide part.
  dload:
    plugin: nil
    build-attributes:
      - enable-patchelf
    stage-packages:
      - libegl1
      - libgl1
      - libglu1-mesa
      - libglx0
      - libxcb-render0
      - libxcursor1
      - libxi6
      - libxkbcommon-x11-0
      - libxrandr2
      - libwayland-egl1
      - libwayland-client0
    stage:
    - -usr/lib/${CRAFT_ARCH_TRIPLET}/dri
  neovide:
    plugin: rust
    source: .
    build-packages:
      - cargo
      - patchelf
      - fontconfig
      - libfontconfig1-dev
      - libfreetype6-dev
      - libxcb-composite0-dev
    stage-packages:
      - libfontconfig1
      - libpng16-16
      - locales-all
      - xdg-user-dirs
    build-attributes:
      - enable-patchelf

apps:
  neovide:
    command: bin/neovide
